version: "3.9" 
services:
  web:
    build: client
    ports:
      - "8000:80"
    depends_on: 
      - server
  server:
    build: server
    environment:
      - MONGO_URL=mongodb://dbserver:27017/vestors
    ports:
      - "5002:5002"
    depends_on: 
      - dbserver
  dbserver:
    image: mongo
    restart: always
